[tool.poetry]
name = "d2ljulia"
version = "0.1.0"
description = ""
authors = ["Nero Blackstone <gf7600gs@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jupyter-book = "^0.15.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
