name: deploy-book

# Only run this when the master branch changes
on:
  pull_request:
    branches:
      - master
  push:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Cancel ongoing documentation build if pushing to branch again before the previous
    # build is finished.
    - name: Cancel ongoing builds and checkout
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    # Install python dependencies
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: '3'

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    # Install julia dependencies
    - name: Set up julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1'

    - name: Instantiate and install Julia dependencies
      run: |
        julia -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          '
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html