name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install python dependencies
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: '3'

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    # Install julia dependencies
    - name: Set up julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1'

    - name: Instantiate and install Julia dependencies
      run: |
        julia -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          ENV["PYTHON"] = ""'
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html